### ISSUE TITLE
Error when Installing in windows python3 using pip

### ISSUE THREAD

**Issue by AndeYashwanth** [kailashbuki/fingerprint#4]
I was trying to install using 
```
pip install fingerprint
```
but it gives an error
```
C:\Users\andey\Documents\GithubDownloadedRepos\dejavu>pip install fingerprint 
Collecting fingerprint
   Using cached fingerprint-0.1.2.tar.gz (3.7 kB)                                                                            
      ERROR: Command errored out with exit status 1: 
         command: 'c:\users\andey\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; 
sys.argv[0] = '"'"'C:\\Users\\andey\\AppData\\Local\\Temp\\pip-install-oibj2130\\fingerprint\\setup.py'"'"'; __file__='"'"'
C:\\Users\\andey\\AppData\\Local\\Temp\\pip-install-oibj2130\\fingerprint\\setup.py'"'"';f=getattr(tokenize, '"'"'open
'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
egg_info --egg-base 'C:\Users\andey\AppData\Local\Temp\pip-install-oibj2130\fingerprint\pip-egg-info'
       cwd: C:\Users\andey\AppData\Local\Temp\pip-install-oibj2130\fingerprint\ 
    Complete output (5 lines):  
    Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:\Users\andey\AppData\Local\Temp\pip-install-oibj2130\fingerprint\setup.py", line 12, in <module>
          long_description=open('README.md').read(),                                                                          
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'  
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

But older version
```
pip install fingerprint==0.1.1
```
works fine though.

**Comment by AndeYashwanth** [comment]
I just saw that #3 fixed the same issue I am facing. So I downloaded the git repo and installed it successfully using setup.py.
Is there any way to make this work with pip install fingerprint also?

**Comment by kailashbuki** [comment]
Thank you @AndeYashwanth for raising the issue. There were some issues with the old setup.py file. I have fixed the issue now. You should be able to install the package with pip now.
